import { db } from "@/server/db";
import { sql } from "@vercel/postgres";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";

// Migration SQL to create PDF tables and group chat support
const MIGRATION_SQL = `
-- Create pdf_documents table
CREATE TABLE IF NOT EXISTS "lightshadow_pdf_document" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"userId" varchar(256) NOT NULL,
	"fileName" varchar(512) NOT NULL,
	"fileUrl" varchar(1024) NOT NULL,
	"pdfAiFileId" varchar(256),
	"uploadthingFileKey" varchar(512),
	"pageCount" integer,
	"createdAt" timestamp with time zone NOT NULL DEFAULT NOW(),
	"updatedAt" timestamp with time zone
);

-- Create index on userId for pdf_documents
CREATE INDEX IF NOT EXISTS "pdf_user_idx" ON "lightshadow_pdf_document" USING btree ("userId");

-- Create chat_pdf_references table
CREATE TABLE IF NOT EXISTS "lightshadow_chat_pdf_reference" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"chatId" integer NOT NULL,
	"pdfDocumentId" integer NOT NULL,
	"createdAt" timestamp with time zone NOT NULL DEFAULT NOW()
);

-- Create indexes for chat_pdf_references
CREATE INDEX IF NOT EXISTS "chat_pdf_chat_idx" ON "lightshadow_chat_pdf_reference" USING btree ("chatId");
CREATE INDEX IF NOT EXISTS "chat_pdf_doc_idx" ON "lightshadow_chat_pdf_reference" USING btree ("pdfDocumentId");

-- Add foreign key constraints (only if they don't exist)
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'lightshadow_chat_pdf_reference_chatId_lightshadow_chat_id_fk'
    ) THEN
        ALTER TABLE "lightshadow_chat_pdf_reference" 
        ADD CONSTRAINT "lightshadow_chat_pdf_reference_chatId_lightshadow_chat_id_fk" 
        FOREIGN KEY ("chatId") REFERENCES "public"."lightshadow_chat"("id") ON DELETE cascade ON UPDATE no action;
    END IF;
END $$;

DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'lightshadow_chat_pdf_reference_pdfDocumentId_lightshadow_pdf_document_id_fk'
    ) THEN
        ALTER TABLE "lightshadow_chat_pdf_reference" 
        ADD CONSTRAINT "lightshadow_chat_pdf_reference_pdfDocumentId_lightshadow_pdf_document_id_fk" 
        FOREIGN KEY ("pdfDocumentId") REFERENCES "public"."lightshadow_pdf_document"("id") ON DELETE cascade ON UPDATE no action;
    END IF;
END $$;

-- Add missing columns to chats table for group chat support
ALTER TABLE "lightshadow_chat" ADD COLUMN IF NOT EXISTS "isGroupChat" boolean NOT NULL DEFAULT false;
ALTER TABLE "lightshadow_chat" ADD COLUMN IF NOT EXISTS "groupName" varchar(256);
ALTER TABLE "lightshadow_chat" ADD COLUMN IF NOT EXISTS "themeColor" varchar(50);

-- Create user_profiles table
CREATE TABLE IF NOT EXISTS "lightshadow_user_profile" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"userId" varchar(256) NOT NULL UNIQUE,
	"username" varchar(100) NOT NULL UNIQUE,
	"avatarUrl" varchar(1024),
	"phoneNumber" varchar(20),
	"uniqueId" varchar(50) NOT NULL UNIQUE,
	"createdAt" timestamp with time zone NOT NULL DEFAULT NOW(),
	"updatedAt" timestamp with time zone
);

CREATE INDEX IF NOT EXISTS "user_profile_user_idx" ON "lightshadow_user_profile" USING btree ("userId");
CREATE INDEX IF NOT EXISTS "user_profile_username_idx" ON "lightshadow_user_profile" USING btree ("username");
CREATE INDEX IF NOT EXISTS "user_profile_unique_id_idx" ON "lightshadow_user_profile" USING btree ("uniqueId");

-- Create contacts table
CREATE TABLE IF NOT EXISTS "lightshadow_contact" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"userId" varchar(256) NOT NULL,
	"contactId" varchar(256) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS "contact_user_idx" ON "lightshadow_contact" USING btree ("userId");
CREATE INDEX IF NOT EXISTS "contact_contact_idx" ON "lightshadow_contact" USING btree ("contactId");
CREATE INDEX IF NOT EXISTS "contact_pair_idx" ON "lightshadow_contact" USING btree ("userId", "contactId");

-- Create chat_participants table
CREATE TABLE IF NOT EXISTS "lightshadow_chat_participant" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"chatId" integer NOT NULL,
	"userId" varchar(256) NOT NULL,
	"joinedAt" timestamp with time zone NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS "chat_participant_chat_idx" ON "lightshadow_chat_participant" USING btree ("chatId");
CREATE INDEX IF NOT EXISTS "chat_participant_user_idx" ON "lightshadow_chat_participant" USING btree ("userId");
CREATE INDEX IF NOT EXISTS "chat_participant_pair_idx" ON "lightshadow_chat_participant" USING btree ("chatId", "userId");

-- Add foreign key constraint for chat_participants
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'lightshadow_chat_participant_chatId_lightshadow_chat_id_fk'
    ) THEN
        ALTER TABLE "lightshadow_chat_participant" 
        ADD CONSTRAINT "lightshadow_chat_participant_chatId_lightshadow_chat_id_fk" 
        FOREIGN KEY ("chatId") REFERENCES "public"."lightshadow_chat"("id") ON DELETE cascade ON UPDATE no action;
    END IF;
END $$;
`;

export async function GET(req: Request) {
  try {
    const { getUser } = getKindeServerSession();
    const user = await getUser();

    if (!user) {
      return new Response("Unauthorized", { status: 401 });
    }

    // Check if tables already exist
    const checkTables = await sql`
      SELECT table_name 
      FROM information_schema.tables 
      WHERE table_schema = 'public' 
      AND table_name IN (
        'lightshadow_pdf_document', 
        'lightshadow_chat_pdf_reference',
        'lightshadow_user_profile',
        'lightshadow_contact',
        'lightshadow_chat_participant'
      )
    `;

    const expectedTables = [
      'lightshadow_pdf_document',
      'lightshadow_chat_pdf_reference',
      'lightshadow_user_profile',
      'lightshadow_contact',
      'lightshadow_chat_participant'
    ];
    
    const existingTableNames = checkTables.rows.map(r => r.table_name);
    const allTablesExist = expectedTables.every(table => existingTableNames.includes(table));

    if (allTablesExist) {
      return new Response(
        JSON.stringify({ 
          success: true, 
          message: "All tables already exist",
          tables: existingTableNames
        }),
        { 
          status: 200,
          headers: { "Content-Type": "application/json" }
        }
      );
    }

    // Run migration
    await sql.query(MIGRATION_SQL);

    // Verify tables were created
    const verifyTables = await sql`
      SELECT table_name 
      FROM information_schema.tables 
      WHERE table_schema = 'public' 
      AND table_name IN (
        'lightshadow_pdf_document', 
        'lightshadow_chat_pdf_reference',
        'lightshadow_user_profile',
        'lightshadow_contact',
        'lightshadow_chat_participant'
      )
    `;

    return new Response(
      JSON.stringify({ 
        success: true, 
        message: "Migration completed successfully",
        tables: verifyTables.rows.map(r => r.table_name)
      }),
      { 
        status: 200,
        headers: { "Content-Type": "application/json" }
      }
    );
  } catch (error: any) {
    console.error("Migration error:", error);
    return new Response(
      JSON.stringify({ 
        success: false, 
        error: error.message,
        details: error.detail 
      }),
      { 
        status: 500,
        headers: { "Content-Type": "application/json" }
      }
    );
  }
}
