import { db } from "@/server/db";
import { sql } from "@vercel/postgres";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";

// Migration SQL to create PDF tables
const MIGRATION_SQL = `
-- Create pdf_documents table
CREATE TABLE IF NOT EXISTS "lightshadow_pdf_document" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"userId" varchar(256) NOT NULL,
	"fileName" varchar(512) NOT NULL,
	"fileUrl" varchar(1024) NOT NULL,
	"pdfAiFileId" varchar(256),
	"uploadthingFileKey" varchar(512),
	"pageCount" integer,
	"createdAt" timestamp with time zone NOT NULL DEFAULT NOW(),
	"updatedAt" timestamp with time zone
);

-- Create index on userId for pdf_documents
CREATE INDEX IF NOT EXISTS "pdf_user_idx" ON "lightshadow_pdf_document" USING btree ("userId");

-- Create chat_pdf_references table
CREATE TABLE IF NOT EXISTS "lightshadow_chat_pdf_reference" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"chatId" integer NOT NULL,
	"pdfDocumentId" integer NOT NULL,
	"createdAt" timestamp with time zone NOT NULL DEFAULT NOW()
);

-- Create indexes for chat_pdf_references
CREATE INDEX IF NOT EXISTS "chat_pdf_chat_idx" ON "lightshadow_chat_pdf_reference" USING btree ("chatId");
CREATE INDEX IF NOT EXISTS "chat_pdf_doc_idx" ON "lightshadow_chat_pdf_reference" USING btree ("pdfDocumentId");

-- Add foreign key constraints (only if they don't exist)
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'lightshadow_chat_pdf_reference_chatId_lightshadow_chat_id_fk'
    ) THEN
        ALTER TABLE "lightshadow_chat_pdf_reference" 
        ADD CONSTRAINT "lightshadow_chat_pdf_reference_chatId_lightshadow_chat_id_fk" 
        FOREIGN KEY ("chatId") REFERENCES "public"."lightshadow_chat"("id") ON DELETE cascade ON UPDATE no action;
    END IF;
END $$;

DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'lightshadow_chat_pdf_reference_pdfDocumentId_lightshadow_pdf_document_id_fk'
    ) THEN
        ALTER TABLE "lightshadow_chat_pdf_reference" 
        ADD CONSTRAINT "lightshadow_chat_pdf_reference_pdfDocumentId_lightshadow_pdf_document_id_fk" 
        FOREIGN KEY ("pdfDocumentId") REFERENCES "public"."lightshadow_pdf_document"("id") ON DELETE cascade ON UPDATE no action;
    END IF;
END $$;
`;

export async function GET(req: Request) {
  try {
    const { getUser } = getKindeServerSession();
    const user = await getUser();

    if (!user) {
      return new Response("Unauthorized", { status: 401 });
    }

    // Check if tables already exist
    const checkTables = await sql`
      SELECT table_name 
      FROM information_schema.tables 
      WHERE table_schema = 'public' 
      AND table_name IN ('lightshadow_pdf_document', 'lightshadow_chat_pdf_reference')
    `;

    if (checkTables.rows.length === 2) {
      return new Response(
        JSON.stringify({ 
          success: true, 
          message: "Tables already exist",
          tables: checkTables.rows.map(r => r.table_name)
        }),
        { 
          status: 200,
          headers: { "Content-Type": "application/json" }
        }
      );
    }

    // Run migration
    await sql.query(MIGRATION_SQL);

    // Verify tables were created
    const verifyTables = await sql`
      SELECT table_name 
      FROM information_schema.tables 
      WHERE table_schema = 'public' 
      AND table_name IN ('lightshadow_pdf_document', 'lightshadow_chat_pdf_reference')
    `;

    return new Response(
      JSON.stringify({ 
        success: true, 
        message: "Migration completed successfully",
        tables: verifyTables.rows.map(r => r.table_name)
      }),
      { 
        status: 200,
        headers: { "Content-Type": "application/json" }
      }
    );
  } catch (error: any) {
    console.error("Migration error:", error);
    return new Response(
      JSON.stringify({ 
        success: false, 
        error: error.message,
        details: error.detail 
      }),
      { 
        status: 500,
        headers: { "Content-Type": "application/json" }
      }
    );
  }
}
