-- Incremental migration: Add PDF tables only
-- This migration assumes lightshadow_chat, lightshadow_message, and lightshadow_post already exist
-- Run this if you already have the base tables

-- Create pdf_documents table
CREATE TABLE IF NOT EXISTS "lightshadow_pdf_document" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"userId" varchar(256) NOT NULL,
	"fileName" varchar(512) NOT NULL,
	"fileUrl" varchar(1024) NOT NULL,
	"pdfAiFileId" varchar(256),
	"uploadthingFileKey" varchar(512),
	"pageCount" integer,
	"createdAt" timestamp with time zone NOT NULL DEFAULT NOW(),
	"updatedAt" timestamp with time zone
);

--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "pdf_user_idx" ON "lightshadow_pdf_document" USING btree ("userId");

--> statement-breakpoint
-- Create chat_pdf_references table
CREATE TABLE IF NOT EXISTS "lightshadow_chat_pdf_reference" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"chatId" integer NOT NULL,
	"pdfDocumentId" integer NOT NULL,
	"createdAt" timestamp with time zone NOT NULL DEFAULT NOW()
);

--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "chat_pdf_chat_idx" ON "lightshadow_chat_pdf_reference" USING btree ("chatId");

--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "chat_pdf_doc_idx" ON "lightshadow_chat_pdf_reference" USING btree ("pdfDocumentId");

--> statement-breakpoint
-- Add foreign key constraints (only if they don't exist)
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'lightshadow_chat_pdf_reference_chatId_lightshadow_chat_id_fk'
    ) THEN
        ALTER TABLE "lightshadow_chat_pdf_reference" 
        ADD CONSTRAINT "lightshadow_chat_pdf_reference_chatId_lightshadow_chat_id_fk" 
        FOREIGN KEY ("chatId") REFERENCES "public"."lightshadow_chat"("id") ON DELETE cascade ON UPDATE no action;
    END IF;
END $$;

--> statement-breakpoint
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'lightshadow_chat_pdf_reference_pdfDocumentId_lightshadow_pdf_document_id_fk'
    ) THEN
        ALTER TABLE "lightshadow_chat_pdf_reference" 
        ADD CONSTRAINT "lightshadow_chat_pdf_reference_pdfDocumentId_lightshadow_pdf_document_id_fk" 
        FOREIGN KEY ("pdfDocumentId") REFERENCES "public"."lightshadow_pdf_document"("id") ON DELETE cascade ON UPDATE no action;
    END IF;
END $$;
