-- Add missing columns to chats table for group chat support
ALTER TABLE "lightshadow_chat" ADD COLUMN IF NOT EXISTS "isGroupChat" boolean NOT NULL DEFAULT false;
ALTER TABLE "lightshadow_chat" ADD COLUMN IF NOT EXISTS "groupName" varchar(256);
ALTER TABLE "lightshadow_chat" ADD COLUMN IF NOT EXISTS "themeColor" varchar(50);

--> statement-breakpoint
-- Create user_profiles table
CREATE TABLE IF NOT EXISTS "lightshadow_user_profile" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"userId" varchar(256) NOT NULL UNIQUE,
	"username" varchar(100) NOT NULL UNIQUE,
	"avatarUrl" varchar(1024),
	"phoneNumber" varchar(20),
	"uniqueId" varchar(50) NOT NULL UNIQUE,
	"createdAt" timestamp with time zone NOT NULL DEFAULT NOW(),
	"updatedAt" timestamp with time zone
);

--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "user_profile_user_idx" ON "lightshadow_user_profile" USING btree ("userId");
CREATE INDEX IF NOT EXISTS "user_profile_username_idx" ON "lightshadow_user_profile" USING btree ("username");
CREATE INDEX IF NOT EXISTS "user_profile_unique_id_idx" ON "lightshadow_user_profile" USING btree ("uniqueId");

--> statement-breakpoint
-- Create contacts table
CREATE TABLE IF NOT EXISTS "lightshadow_contact" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"userId" varchar(256) NOT NULL,
	"contactId" varchar(256) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL DEFAULT NOW()
);

--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "contact_user_idx" ON "lightshadow_contact" USING btree ("userId");
CREATE INDEX IF NOT EXISTS "contact_contact_idx" ON "lightshadow_contact" USING btree ("contactId");
CREATE INDEX IF NOT EXISTS "contact_pair_idx" ON "lightshadow_contact" USING btree ("userId", "contactId");

--> statement-breakpoint
-- Create chat_participants table
CREATE TABLE IF NOT EXISTS "lightshadow_chat_participant" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"chatId" integer NOT NULL,
	"userId" varchar(256) NOT NULL,
	"joinedAt" timestamp with time zone NOT NULL DEFAULT NOW()
);

--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "chat_participant_chat_idx" ON "lightshadow_chat_participant" USING btree ("chatId");
CREATE INDEX IF NOT EXISTS "chat_participant_user_idx" ON "lightshadow_chat_participant" USING btree ("userId");
CREATE INDEX IF NOT EXISTS "chat_participant_pair_idx" ON "lightshadow_chat_participant" USING btree ("chatId", "userId");

--> statement-breakpoint
-- Add foreign key constraint for chat_participants
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'lightshadow_chat_participant_chatId_lightshadow_chat_id_fk'
    ) THEN
        ALTER TABLE "lightshadow_chat_participant" 
        ADD CONSTRAINT "lightshadow_chat_participant_chatId_lightshadow_chat_id_fk" 
        FOREIGN KEY ("chatId") REFERENCES "public"."lightshadow_chat"("id") ON DELETE cascade ON UPDATE no action;
    END IF;
END $$;
